# Generated by Django 4.0.5 on 2022-07-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('logo_pic', models.ImageField(upload_to='app/img/company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('min_salary', models.BigIntegerField()),
                ('max_salary', models.BigIntegerField()),
                ('job_type', models.CharField(max_length=150)),
                ('jobcategory', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('highestedu', models.CharField(max_length=150)),
                ('experience', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('shift', models.CharField(max_length=150)),
                ('jobdescription', models.CharField(max_length=500)),
                ('profile_pic', models.ImageField(upload_to='app/img/candidate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermaster')),
            ],
        ),
    ]
