# Generated by Django 4.0.5 on 2022-07-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_candidate_max_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=250)),
                ('companyname', models.CharField(max_length=250)),
                ('companyaddress', models.CharField(max_length=250)),
                ('jobdescription', models.TextField(max_length=500)),
                ('qualification', models.CharField(max_length=250)),
                ('responsibility', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('companywebsite', models.CharField(max_length=100)),
                ('companyemail', models.EmailField(max_length=50)),
                ('companycontact', models.CharField(max_length=20)),
                ('salarypackage', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('logo', models.ImageField(upload_to='app/img/jobpost')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.CharField(max_length=100)),
                ('max_salary', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='app/resume')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdetails')),
            ],
        ),
    ]
