# Generated by Django 4.0.5 on 2022-07-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobdetails_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='is_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='is_upload',
            field=models.TimeField(auto_now=True),
        ),
    ]
